name: Build ESP32 firmware   # 工作流名称

on:
  push:
    branches: [main]         # main 分支 push 时触发
  pull_request:
    branches: [main]         # PR 也触发（可选）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码（包含子模块）
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2. 缓存 IDF 工具，节省下载时间（可选）
      - name: Cache IDF tools
        uses: actions/cache@v3
        with:
          path: /opt/esp        # ← 官方镜像实际安装位置
          key: idf-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}


      # 3. 编译 ESP32 工程
      - name: Build ESP32 project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.1      # 与本地一致即可
          target: esp32
          path: '.'                    # 工程根目录
